[package]
name = "ubersimx-messaging"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
async-nats = "0.42.0"
async-trait = "0.1.89"
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
